// Property data + metric definitions
const PROPERTIES = [
  {
    id: 'p1',
    address: '27 Nioka Street, Chadstone VIC',
    type: 'House',
    typeIcon: 'Home',
    winner: true,
    price: 1875000, priceLabel: '$1,875,000',
    overallScore: 90.11,
    landSize: '620 m²', propertySize: '203 m²',
    beds: 5, baths: 3, cars: 4,
    growth: 3.76, growthSign: 'pos',
    summary: 'After analyzing all properties against your Principal Place of Residence investment goal, this property emerged as the top recommendation. It offers the best combination of location quality, property features, and value alignment with your specific requirements.',
    summaryB: 'This property scored highest across key metrics including neighborhood safety, school quality, commute accessibility, and overall liveability factors that matter most for your investment strategy.',
    estValue: 1875000, estValueLabel: '$1.88M',
    unitSize: '—',
    ownedOutright: 24.1, ownedMortgage: 23.8, rented: 50.4, other: 1.6,
    ownerOccupier: 61.0,
    crimeScore: 12, violentCrimes: 8.2, propertyCrimes: 14.3,
    schoolScore: 88, commuteScore: 82, servicesScore: 82,
    orientation: 'NE',
    powerline: true, heritage: true, flood: true, bushfire: true, mainRoad: true,
    // Overview-card metrics
    gentrification: 45.2,
    infrastructure: 85,
    priceGrowth: 62.5, priceGrowthLabel: '62.5%', priceGrowthDir: 'pos',
    vacancyRate: 9.3,
    publicHousing: 2.7,
    populationGrowth: 20.28,
    risks: { flood: true, bushfire: true, mainRoad: false, powerline: true, heritage: true },
  },
  {
    id: 'p2',
    address: '50 Munro Avenue Ashburton, VIC 3147',
    type: 'House',
    typeIcon: 'Home',
    winner: false,
    price: 1200000, priceLabel: '$1,200,000',
    overallScore: 96.86,
    landSize: '620 m²', propertySize: '203 m²',
    beds: 5, baths: 3, cars: 2,
    growth: 1.88, growthSign: 'pos',
    summary: 'Strong-fundamentals property with excellent owner occupier ratio and steady growth.',
    estValue: 1200000, estValueLabel: '$1.2M',
    unitSize: '—',
    ownedOutright: 30, ownedMortgage: 35, rented: 33, other: 2,
    ownerOccupier: 73.7,
    crimeScore: 12, violentCrimes: 8.2, propertyCrimes: 14.3,
    schoolScore: 90, commuteScore: 75, servicesScore: 80,
    orientation: 'N',
    powerline: false, heritage: true, flood: false, bushfire: true, mainRoad: false,
    gentrification: 48.0,
    infrastructure: 92,
    priceGrowth: -4.4, priceGrowthLabel: '-4.4%', priceGrowthDir: 'neg',
    vacancyRate: 8.0,
    publicHousing: 3.4,
    populationGrowth: 12.81,
    risks: { flood: true, bushfire: true, mainRoad: false, powerline: true, heritage: true },
  },
  {
    id: 'p3',
    address: '48 Haig Street Burwood, VIC 3125',
    type: 'House',
    typeIcon: 'Home',
    winner: false,
    price: 2300000, priceLabel: '$2,300,000',
    overallScore: 96.71,
    landSize: '620 m²', propertySize: '203 m²',
    beds: 5, baths: 4, cars: 3,
    growth: 2.42, growthSign: 'pos',
    summary: 'Premium positioning in Burwood with above-average lot size and favourable infrastructure score.',
    estValue: 2300000, estValueLabel: '$2.3M',
    unitSize: '—',
    ownedOutright: 28, ownedMortgage: 27, rented: 43, other: 2,
    ownerOccupier: 55.7,
    crimeScore: 18, violentCrimes: 9.1, propertyCrimes: 16.8,
    schoolScore: 86, commuteScore: 72, servicesScore: 88,
    orientation: 'N',
    powerline: true, heritage: true, flood: true, bushfire: true, mainRoad: false,
    gentrification: 45.2,
    infrastructure: 89,
    priceGrowth: 14.8, priceGrowthLabel: '14.8%', priceGrowthDir: 'pos',
    vacancyRate: 15.3,
    publicHousing: 3.2,
    populationGrowth: 5.31,
    risks: { flood: true, bushfire: true, mainRoad: false, powerline: true, heritage: true },
  },
  {
    id: 'p4',
    address: '9 Ninth Avenue, Campsie 2194, NSW',
    type: 'House',
    typeIcon: 'Home',
    winner: false,
    price: 730000, priceLabel: '$730,000',
    overallScore: 78.42,
    landSize: '410 m²', propertySize: '118 m²',
    beds: 3, baths: 2, cars: 1,
    growth: -0.42, growthSign: 'neg',
    summary: 'A smaller house priced just under budget. Subdued growth and a smaller 410m² lot pull down its overall score despite sitting in a safer catchment area.',
    estValue: 730000, estValueLabel: '$730K',
    unitSize: '—',
    ownedOutright: 26.3, ownedMortgage: 31.2, rented: 41.1, other: 1.4,
    ownerOccupier: 57.5,
    crimeScore: 9, violentCrimes: 6.4, propertyCrimes: 11.2,
    schoolScore: 81, commuteScore: 62, servicesScore: 74,
    orientation: 'E',
    powerline: true, heritage: true, flood: true, bushfire: true, mainRoad: true,
    gentrification: 38.0,
    infrastructure: 74,
    priceGrowth: -0.4, priceGrowthLabel: '-0.4%', priceGrowthDir: 'neg',
    vacancyRate: 6.1,
    publicHousing: 2.0,
    populationGrowth: 3.12,
    risks: { flood: true, bushfire: true, mainRoad: true, powerline: true, heritage: true },
  },
  {
    id: 'p5',
    address: '48 Evaline Street, Campsie 2194, NSW',
    type: 'Unit',
    typeIcon: 'Building',
    winner: false,
    price: 620000, priceLabel: '$620,000',
    overallScore: 82.14,
    landSize: '—', propertySize: '—',
    beds: 2, baths: 1, cars: 1,
    growth: 2.95, growthSign: 'pos',
    summary: 'A well-priced 2BR unit comfortably within budget. Limited land component but excellent walkability scores and proximity to the train station.',
    estValue: 620000, estValueLabel: '$620K',
    unitSize: '68 m²',
    ownedOutright: 19.5, ownedMortgage: 20.2, rented: 58.4, other: 1.9,
    ownerOccupier: 39.7,
    crimeScore: 14, violentCrimes: 8.9, propertyCrimes: 15.1,
    schoolScore: 66, commuteScore: 92, servicesScore: 94,
    orientation: 'NW',
    powerline: false, heritage: true, flood: false, bushfire: false, mainRoad: false,
    gentrification: 52.0,
    infrastructure: 80,
    priceGrowth: 8.2, priceGrowthLabel: '8.2%', priceGrowthDir: 'pos',
    vacancyRate: 11.2,
    publicHousing: 2.4,
    populationGrowth: 9.05,
    risks: { flood: false, bushfire: false, mainRoad: false, powerline: false, heritage: true },
  },
];

const METRICS = [
  { id:'details', label:'Property Details', icon:'MapPin', type:'details' },
  { id:'images', label:'Property Images', icon:'ImageIcon', type:'images' },
  { id:'price', label:'Price', icon:'DollarSign', type:'price' },
  { id:'score', label:'Overall Score', icon:'Target', type:'score', tip:'Weighted score against your goal & preferences' },
  { id:'summary', label:'Property Summary', icon:'Sparkles', type:'summary' },
  { id:'estValue', label:'Estimated Value', icon:'DollarSign', type:'estValue' },
  { id:'landSize', label:'Land Size', icon:'Layers', type:'text', field:'landSize' },
  { id:'propertySize', label:'Property Size', icon:'Home', type:'text', field:'propertySize' },
  { id:'unitSize', label:'Unit Size', icon:'Maximize', type:'text', field:'unitSize' },
  { id:'owner', label:'Owner Occupier', icon:'User', type:'donut' },
  { id:'crime', label:'Crime Score', icon:'Shield', type:'crime' },
  { id:'school', label:'School Score', icon:'School', type:'progress', field:'schoolScore' },
  { id:'commute', label:'Commute Score', icon:'Car', type:'progress', field:'commuteScore' },
  { id:'orientation', label:'Orientation', icon:'Compass', type:'text', field:'orientation' },
  { id:'services', label:'Services Score', icon:'Store', type:'progress', field:'servicesScore' },
  { id:'powerline', label:'Powerline Proximity', icon:'Zap', type:'bool', field:'powerline' },
  { id:'heritage', label:'Heritage Overlay', icon:'Landmark', type:'bool', field:'heritage' },
  { id:'flood', label:'Flood Zone', icon:'Droplets', type:'bool', field:'flood' },
  { id:'bushfire', label:'Bushfire Zone', icon:'Flame', type:'bool', field:'bushfire' },
  { id:'mainRoad', label:'On Main road?', icon:'Navigation', type:'bool', field:'mainRoad' },
];

Object.assign(window, { PROPERTIES, METRICS });
